version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5299:5299"
      - "7186:7186"

  neo4j:
    image: neo4j:5.16.0
    environment:
      NEO4J_AUTH: none
    volumes:
      - neo4j-data:/data
    ports:
      - "7474:7474"
      - "7687:7687"

volumes:
  neo4j-data:
    driver: local
